variable "project" {
  description = "Project name will be used for naming resources in pattern %PROJECT_NAME%-%ENVIRONMENT_NAME%"
  default     = "project"
}

variable "environment" {
  description = "Environment name will be used for naming resources in pattern %PROJECT_NAME%-%ENVIRONMENT_NAME%"
  default     = "test"
}

variable "tags" {
  type        = "map"
  description = "A mapping of tags to assign to the queue."
  default     = {}
}



variable "name" {
  type        = "string"
  description = "The friendly name for the SNS topic. By default generated by Terraform."
  default     = ""
}

variable "name_prefix" {
  type        = "string"
  description = "The friendly name for the SNS topic. Conflicts with name."
  default     = ""
}

variable "display_name" {
  type        = "string"
  description = "The display name for the SNS topic"
  default     = ""
}

variable "policy" {
  type        = "string"
  description = "The fully-formed AWS policy as JSON. For more information about building AWS IAM policy documents with Terraform, see the AWS IAM Policy Document Guide."
  default     = ""
}

variable "delivery_policy" {
  type        = "string"
  description = "The SNS delivery policy. More on AWS documentation"
  default     = ""
}

variable "application_success_feedback_role_arn" {
  type        = "string"
  description = "The IAM role permitted to receive success feedback for this topic"
  default     = ""
}

variable "application_success_feedback_sample_rate" {
  type        = "string"
  description = "Percentage of success to sample"
  default     = ""
}

variable "application_failure_feedback_role_arn" {
  type        = "string"
  description = "IAM role for failure feedback"
  default     = ""
}

variable "http_success_feedback_role_arn" {
  type        = "string"
  description = "The IAM role permitted to receive success feedback for this topic"
  default     = ""
}

variable "http_success_feedback_sample_rate" {
  description = "Percentage of success to sample"
  default     = 100
}

variable "http_failure_feedback_role_arn" {
  type        = "string"
  description = "IAM role for failure feedback"
  default     = ""
}

variable "kms_master_key_id" {
  type        = "string"
  description = "The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK. For more information, see Key Terms"
  default     = ""
}

variable "lambda_success_feedback_role_arn" {
  type        = "string"
  description = "The IAM role permitted to receive success feedback for this topic"
  default     = ""
}

variable "lambda_success_feedback_sample_rate" {
  description = "Percentage of success to sample"
  default     = 100
}

variable "lambda_failure_feedback_role_arn" {
  type        = "string"
  description = "IAM role for failure feedback"
  default     = ""
}

variable "sqs_success_feedback_role_arn" {
  type        = "string"
  description = "The IAM role permitted to receive success feedback for this topic"
  default     = ""
}

variable "sqs_success_feedback_sample_rate" {
  description = "Percentage of success to sample"
  default     = 100
}

variable "sqs_failure_feedback_role_arn" {
  type        = "string"
  description = "IAM role for failure feedback"
  default     = ""
}

variable "topic_subscription" {
  type        = "map"
  description = "protocol and endpoint for topic subscription. The protocol to use. The possible values for this are: sqs, sms, lambda, application. (http or https are partially supported, see below) (email is option but unsupported, see below). The endpoint to send data to, the contents will vary with the protocol. (see below for more information)"
  default     = {
    protocol = ""
    endpoint = ""
  }
}

variable "endpoint_auto_confirms" {
  type        = "string"
  description = "Indicating whether the end point is capable of auto confirming subscription e.g., PagerDuty (default is false)"
  default     = "false"
}

variable "confirmation_timeout_in_minutes" {
  description = "Indicating number of minutes to wait in retying mode for fetching subscription arn before marking it as failure. Only applicable for http and https protocols (default is 1 minute)."
  default     = 1
}

variable "raw_message_delivery" {
  type        = "string"
  description = "Indicating whether or not to enable raw message delivery (the original message is directly passed, not wrapped in JSON with the original message in the message property) (default is false)."
  default     = "false"
}

